version: '3.1'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: matrix_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: zetaprime1
    ports:
    - "5432:5432"
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  postgres: